.TH SDBD 8 LOCAL

.SH NAME
sdbd

.SH SYNOPSIS
.B sdbd
[-d] [-f] port

.SH DESCRIPTION
.I sdbd
allows applications using libsdb to access databases without linking with
the database client libraries. It also allows access to databases that
are located on a different host, even if they don't have a networking
protocol.

.SH SEE ALSO

Sample client in sdbd_client.c

.SH AUTHOR
Copyright (C) 2000-2002 Ulric Eriksson <ulric@siag.nu>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the Licence, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Library General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.

